### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by LuuuFan** [LuuuFan/Celp#3]
- [x] Backend: DB, model, controller, views
- [x]  Redux Loop: ajax, actions, reducer
- [x]  Presentational Components
- [x]  Styling
- [x]  Smooth, bug-free navigation
- [x]  Adequate and appropriate seeds

**Comment by LuuuFan** [comment]
Minor styling issues on heroku need to be fixed later

**Comment by xnanodax** [comment]
- [x] Add a demo user login
- [x] Accessing a random route like `/#/oweiniouewbrviuwebv` should redirect to either `/`, `/login`, or `/signup`

**Comment by LuuuFan** [comment]
Demo user login added, but cannot login, need help tomorrow

**Comment by LuuuFan** [comment]
Checked demo user, it's working on heroku, but not working on local :(

**Comment by LuuuFan** [comment]
Thanks Cynthia~~finished. :D

**Comment by xnanodax** [comment]
Great work!
Before I close this issue, I would decrease the amount of the user has to wait for the demo login to actually login. This may take too long and they may think its broken/not working before it actually logs in.

**Comment by LuuuFan** [comment]
Done. decrease it to 1 second

**Comment by LuuuFan** [comment]
Fixed jumping header in homepage
speed up the demo login
adjusted font size of search bar, but it might looks different depends on screen resollution
pending fix - dropdown close

**Comment by xnanodax** [comment]
Awesome work. Core functionality is done.
